// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lybqfxrtvnzzcnbddtsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YnFmeHJ0dm56emNuYmRkdHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDExMTYsImV4cCI6MjA2NjAxNzExNn0.kkxGzkDsv9G56d091Ev4BTJEMoZbjkuk9gXYYQpAk7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);